### ISSUE TITLE
Code seems to break with React 0.14

### ISSUE THREAD

**Issue by jean-Phil** [react-d3/react-d3-core#12]
Hello Chilijung,

First, kudos for this endeavour.  I really like your take on react and D3 integration.

I tried running the examples in React 0.14, but without success.
I got an...
<pre>Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.</pre>

I was wondering: Have you done any testing yourself? 

Is **react-faux-dom** the culprit?

**Comment by chilijung** [comment]
hi @jean-Phil, could you provide the code are you trying? It seems like the error message point out that u select a DOM that is not exist while rendering.

```js
React.render(
    ...
  // make sure getElementById('id') get the existing DOM in HTML
  , document.getElementById('blank-legend')
  )
```

**Comment by jean-Phil** [comment]
Hello @chilijung,

Thank you for your prompt reply.  
...That is the first thing I checked... The code was very simple. I pasted the legend example into a js file: 
```
"use strict";
var React = require('react');
var Legend = require('react-d3-core').Legend;

(function() {
  var width = 960,
    height = 500,
    margins = {top: 40, right: 50, bottom: 40, left: 50},
    legendClassName = "test-legend-class",
    legendPosition = 'left',
    legendOffset = 90,
    chartSeries = [
      {
        field: 'Under 5 Years',
        name: 'Under 5 Years',
        color: '#1f77b4'
      },
      {
        field: '5 to 13 Years',
        name: '5 to 13 Years',
        color: '#ff7f0e'
      },
      {
        field: '14 to 17 Years',
        name: '14 to 17 Years',
        color: '#2ca02c'
      },
      {
        field: '18 to 24 Years',
        name: '18 to 24 Years',
        color: '#d62728'
      },
      {
        field: '25 to 44 Years',
        name: '25 to 44 Years',
        color: '#9467bd'
      },
      {
        field: '45 to 64 Years',
        name: '45 to 64 Years',
        color: '#8c564b'
      },
      {
        field: '65 Years and Over',
        name: '65 Years and Over',
        color: '#e377c2'
      },

    ]

  React.render(
    <svg width= {width} height= {height}>
      <rect height= {"100%"} width= {"100%"} fill= {"#CCC"} />
      <Legend
        width= {width}
        height= {height}
        margins= {margins}
        legendClassName= {legendClassName}
        legendPosition= {legendPosition}
        legendOffset= {legendOffset}
        chartSeries = {chartSeries}
      />
    </svg>
  , document.getElementById('blank-legend')
  )
})()
```
Everything seems to appear just fine in the "webpacked" output js file.  Here's the html:
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="./node_modules/react-d3-core/css/axis.css">
</head>
<body>
	<div id="blank-legend"></div>
</body>
<script src="./dist/legend.js"></script>
</html>
```

---

Upon reading your reply, I downloaded the **react-d3-example** repo, and updated **React** to 0.14.  The few examples I tried seem to be using React 0.14 and they work. I didn't dig very deep, though.   
**NOTE:** _While we're at it, there are two things which would need to be updated in the HTML files:_
* utf-8 charset declarations
* the paths to the dist folder is only one level up, not two.

If you'd like me to test or do anything, please let me know.  I'll keep getting more familiar with your code and try and figure out what's wrong with this little snippet.  Until then, thank you!

JP

**Comment by chilijung** [comment]
close this for now, I've moved all repo's core, basic, tooltip, brush... to react@0.14
