### ISSUE TITLE
ShowLegend = false has no effect

### ISSUE THREAD

**Issue by bradtwurst** [react-d3/react-d3-core#29]
from what I can tell in the examples and docs, ShowLegend is a bool that determines if the legend is shown.

However, ShowLegend={false} appears to have no effect.

For example, using the PieChart example, adding ShowLegend={false} does nothing.

Am I missing something stupid?

James

**Comment by chilijung** [comment]
Hi, @bradtwurst  this is fixed in latest https://github.com/react-d3/react-d3-basic. Thanks for reporting this issue.
