### ISSUE TITLE
Does react-d3 support server-side rendering?

### ISSUE THREAD

**Issue by greim** [react-d3/react-d3-core#46]
I'm currently evaluating react charting solutions, and react-d3 looks like a solid option. However, I have a hard requirement to be able to render charts directly to HTML strings, outside the context of a browser and otherwise without using a headless DOM implementation.

The reason I ask is because I was given to understand d3 needs to operate directly on the DOM, so I'm wondering how that works with React, which can `renderToString()` when no DOM is present.

Thanks!

**Comment by Anima-t3d** [comment]
Did you take a lookt at [react-d3-server-example](https://github.com/react-d3/react-d3-server-example)?

> A simple example of server-side rendering with react-d3.

**Comment by greim** [comment]
Ah, nice, thanks!
